/**
 * EuroDat OpenAPI Spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.eurodat.brokerextension.openApiClient.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param type 
 * @param includedIn 
 */

data class Action (

    @Json(name = "type")
    val type: kotlin.String? = null,

    @Json(name = "includedIn")
    val includedIn: kotlin.String? = null

)

