/**
 * EuroDat OpenAPI Spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.eurodat.brokerextension.openApiClient.model

import org.eurodat.brokerextension.openApiClient.model.Criterion

import com.squareup.moshi.Json

/**
 * 
 *
 * @param criteria 
 */

data class AssetSelectorExpression (

    @Json(name = "criteria")
    val criteria: kotlin.collections.List<Criterion>? = null

)

