/**
 * EuroDat OpenAPI Spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.eurodat.brokerextension.openApiClient.model

import org.eurodat.brokerextension.openApiClient.model.AssetSelectorExpression
import org.eurodat.brokerextension.openApiClient.model.Policy

import com.squareup.moshi.Json

/**
 * 
 *
 * @param id 
 * @param accessPolicy 
 * @param contractPolicy 
 * @param selectorExpression 
 */

data class ContractDefinition (

    @Json(name = "id")
    val id: kotlin.String? = null,

    @Json(name = "accessPolicy")
    val accessPolicy: Policy? = null,

    @Json(name = "contractPolicy")
    val contractPolicy: Policy? = null,

    @Json(name = "selectorExpression")
    val selectorExpression: AssetSelectorExpression? = null

)

