/**
 * EuroDat OpenAPI Spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.eurodat.brokerextension.openApiClient.model


import com.squareup.moshi.Json

/**
 * 
 *
 * @param left 
 * @param op 
 * @param right 
 */

data class Criterion (

    @Json(name = "left")
    val left: kotlin.Any? = null,

    @Json(name = "op")
    val op: kotlin.String? = null,

    @Json(name = "right")
    val right: kotlin.Any? = null

)

