/**
 * EuroDat OpenAPI Spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.eurodat.brokerextension.openApiClient.model

import org.eurodat.brokerextension.openApiClient.model.Duty
import org.eurodat.brokerextension.openApiClient.model.Permission
import org.eurodat.brokerextension.openApiClient.model.Prohibition

import com.squareup.moshi.Json

/**
 * 
 *
 * @param uid 
 * @param permissions 
 * @param prohibitions 
 * @param obligations 
 * @param extensibleProperties 
 * @param inheritsFrom 
 * @param assigner 
 * @param assignee 
 * @param target 
 * @param atType 
 */

data class Policy (

    @Json(name = "uid")
    val uid: kotlin.String? = null,

    @Json(name = "permissions")
    val permissions: kotlin.collections.List<Permission>? = null,

    @Json(name = "prohibitions")
    val prohibitions: kotlin.collections.List<Prohibition>? = null,

    @Json(name = "obligations")
    val obligations: kotlin.collections.List<Duty>? = null,

    @Json(name = "extensibleProperties")
    val extensibleProperties: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null,

    @Json(name = "inheritsFrom")
    val inheritsFrom: kotlin.String? = null,

    @Json(name = "assigner")
    val assigner: kotlin.String? = null,

    @Json(name = "assignee")
    val assignee: kotlin.String? = null,

    @Json(name = "target")
    val target: kotlin.String? = null,

    @Json(name = "@type")
    val atType: Policy.AtType? = null

) {

    /**
     * 
     *
     * Values: sET,oFFER,cONTRACT
     */
    enum class AtType(val value: kotlin.String) {
        @Json(name = "SET") sET("SET"),
        @Json(name = "OFFER") oFFER("OFFER"),
        @Json(name = "CONTRACT") cONTRACT("CONTRACT");
    }
}

