/**
 * EuroDat OpenAPI Spec
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package org.eurodat.brokerextension.openApiClient.model

import org.eurodat.brokerextension.openApiClient.model.Asset
import org.eurodat.brokerextension.openApiClient.model.Policy

import com.squareup.moshi.Json

/**
 * 
 *
 * @param participantId 
 * @param participantConnectorAddress 
 * @param ownerId 
 * @param contentType 
 * @param asset 
 * @param policy 
 * @param provider 
 * @param consumer 
 */

data class ProviderRequest (

    @Json(name = "participantId")
    val participantId: kotlin.String? = null,

    @Json(name = "participantConnectorAddress")
    val participantConnectorAddress: kotlin.String? = null,

    @Json(name = "ownerId")
    val ownerId: kotlin.String? = null,

    @Json(name = "contentType")
    val contentType: kotlin.String? = null,

    @Json(name = "asset")
    val asset: Asset? = null,

    @Json(name = "policy")
    val policy: Policy? = null,

    @Json(name = "provider")
    val provider: java.net.URI? = null,

    @Json(name = "consumer")
    val consumer: java.net.URI? = null

)

