name: CI

on:
  push:
    branches:
      - '**'

jobs:

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
          cache: gradle
      - name: Build DataSpaceConnector
        run: ./DataSpaceConnector/gradlew -p ./DataSpaceConnector publishToMavenLocal
      - name: Build, check and test project
        run: ./gradlew assemble ktlintCheck detekt test --no-daemon --stacktrace
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: TestReport
          path: ./**/build/reports
      - name: Upload JaCoCo Unit Tests Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: JaCoCoEDCUnitTests
          path: ./*/build/jacoco/*.exec
      - name: Run e2etest
        if: always()
        run: ./dataland-edc-server/test/e2etest.sh
        env:
          TRUSTEE_IP: ${{ secrets.TRUSTEE_IP }}
          TRUSTEE_CREDENTIALS: ${{ secrets.TRUSTEE_CREDENTIALS }}
          TUNNEL_STARTUP_LINK: ${{ secrets.TUNNEL_STARTUP_LINK }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          EDC_API_AUTH_KEY: ${{ secrets.EDC_API_AUTH_KEY }}
          EDC_API_CONTROL_AUTH_APIKEY_VALUE: ${{ secrets.EDC_API_CONTROL_AUTH_APIKEY_VALUE }}
          EDC_KEYSTORE_PASSWORD: ${{ secrets.EDC_KEYSTORE_PASSWORD }}
      - name: Upload EDC Server log file
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: EdcServerLog
          path: ./edc_server.log
      - name: Upload JaCoCo E2E Tests Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: JaCoCoEDCE2ETests
          path: ./dataland-edc-server/build/jacoco/*.exec

  sonar:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - unit-tests
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
          cache: gradle
      - name: Build project
        run: ./gradlew assemble --no-daemon --stacktrace
      - uses: actions/download-artifact@v2
        with:
          name: JaCoCoEDCUnitTests
      - uses: actions/download-artifact@v2
        with:
          name: JaCoCoEDCE2ETests
      - name: Generate jacocoTestReport and run Sonar
        if: always()
        run: |
          ./gradlew jacocoTestReport --no-daemon --stacktrace
          ./gradlew sonarqube --no-daemon --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  summary:
    runs-on: ubuntu-latest
    if: success()
    needs:
      - sonar
    steps:
      - name: Summary of this workflow's overall outcome
        run: exit 0
