name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'


jobs:

  run-checks:
    runs-on: ubuntu-latest
    #if: always()
    #if: github.event_name != 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v2
      - name: Check formatting and code convention by using base image from GitHub Registry
        run: |
          docker run -v $(pwd):/app:rw ghcr.io/d-fine/datalandedc/temurinbase:latest \
          /app/gradlew -p /app ktlintcheck detekt --no-daemon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: $GITHUB_ACTOR

  sonar:
    runs-on: ubuntu-latest
    if: always()
#    needs:
#      - e2e-tests
#      - unit-tests-backend
#      - unit-tests-frontend
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Build project
        run: ./gradlew assemble --no-daemon
#      - uses: actions/download-artifact@v2
#        with:
#          name: JaCoCoResultsUnitTests
#      - uses: actions/download-artifact@v2
#        with:
#          name: JaCoCoResultsE2ETest
#      - uses: actions/download-artifact@v2
#        with:
#          name: lcovResultsUnit
#          path: fe-coverage/unit
#      - uses: actions/download-artifact@v2
#        with:
#          name: lcovResultsE2E
#          path: fe-coverage/e2e
      - name: Generate jacocoTestReport and run Sonar
        if: always()
        run: ./gradlew sonarqube --no-daemon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  summary:
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Summary of this workflow's overall outcome
        run: exit 0
