name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'

jobs:

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Add gitlab to know hosts
        run: |
          mkdir -m 700 ~/.ssh 
          echo "gitlab.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsj2bNKTBSpIYDEGk9KxsGh3mySTRgMtXL583qmBpzeQ+jqCMRgBqB98u3z++J1sKlXHWfM9dyhSevkMwSbhoR8XIq/U0tCNyokEi/ueaBMCvbcTHhO7FcwzY92WK4Yt0aGROY5qX2UKSeOvuP4D6TPqKF1onrSzH9bx9XUf2lEdWT/ia1NEKjunUqu1xOB/StKDHMoX4/OKyIzuS0q/T1zOATthvasJFoPrAjkohTyaDUz2LN5JoH839hViyEG82yB+MjcFV5MU3N1l1QL3cVUCh93xSaua1N85qivl+siMkPGbO5xR/En4iEY6K2XPASUEMaieWVNTRCtJ4S8H+9" >> ~/.ssh/known_hosts
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Build, check and test project
        run: ./gradlew assemble ktlintCheck detekt test --no-daemon
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: TestReport
          path: ./**/build/reports
      - name: Upload JaCoCo EDC Dummy Server Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: JaCoCoEDCDummyUnitTests
          path: ./*/build/jacoco/*.exec
      - name: Upload JaCoCo API Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: JaCoCoAPIUnitTests
          path: ./api/build/jacoco/*.exec
  sonar:
    runs-on: ubuntu-latest
    if: always()
    needs:
      - unit-tests
    steps:
      - name: Add gitlab to know hosts
        run: echo "gitlab.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsj2bNKTBSpIYDEGk9KxsGh3mySTRgMtXL583qmBpzeQ+jqCMRgBqB98u3z++J1sKlXHWfM9dyhSevkMwSbhoR8XIq/U0tCNyokEi/ueaBMCvbcTHhO7FcwzY92WK4Yt0aGROY5qX2UKSeOvuP4D6TPqKF1onrSzH9bx9XUf2lEdWT/ia1NEKjunUqu1xOB/StKDHMoX4/OKyIzuS0q/T1zOATthvasJFoPrAjkohTyaDUz2LN5JoH839hViyEG82yB+MjcFV5MU3N1l1QL3cVUCh93xSaua1N85qivl+siMkPGbO5xR/En4iEY6K2XPASUEMaieWVNTRCtJ4S8H+9" >> ~/.ssh/known_hosts
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Build project
        run: ./gradlew assemble --no-daemon
      - uses: actions/download-artifact@v2
        with:
          name: JaCoCoEDCDummyUnitTests
      - uses: actions/download-artifact@v2
        with:
          name: JaCoCoAPIUnitTests
      - name: Generate jacocoTestReport and run Sonar
        if: always()
        run: |
          ./gradlew jacocoTestReport --no-daemon
          find . -type f -iname "*.exec";
          ./gradlew sonarqube --no-daemon
          find . -type f -name jacocoTestReport.xml;
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  summary:
    runs-on: ubuntu-latest
    if: success()
    needs:
      - sonar
    steps:
      - name: Summary of this workflow's overall outcome
        run: exit 0
