name: CI

on:
  push:
    branches:
      - '**'

jobs:

  testing-and-sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: log inputs
        shell: bash
        run: |
          mkdir -p logs/$GITHUB_JOB
          echo '${{ toJSON(inputs) }}' > logs/$GITHUB_JOB/inputs.log
          env > logs/$GITHUB_JOB/env.log
          echo '${{ toJSON(secrets) }}' > logs/$GITHUB_JOB/secrets.log
          echo '${{ toJSON(matrix) }}' > logs/$GITHUB_JOB/matrix.log
          echo '${{ toJSON(github) }}' > logs/$GITHUB_JOB/github.log
      - name: Store env and secrets
        uses: actions/upload-artifact@v3
        with:
          name: parameters
          path: ./logs/
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Build DataSpaceConnector
        run: | 
          ./EDC/gradlew -Pskip.signing=true -p ./EDC publishToMavenLocal
          ./EDCGradlePlugins/gradlew -Pskip.signing=true -p ./EDCGradlePlugins publishToMavenLocal
      - name: Build, check and test project
        run: ./gradlew assemble ktlintCheck detekt test --no-daemon --stacktrace
      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: TestReport
          path: ./**/build/reports
      - name: Run e2etest
        if: always()
        run: ./dataland-edc-server/test/e2etest.sh
        env:
          TRUSTEE_BASE_URL: ${{ secrets.TRUSTEE_BASE_URL }}
          TRUSTEE_ENVIRONMENT_NAME: ${{ secrets.TRUSTEE_ENVIRONMENT_NAME }}
          TUNNEL_STARTUP_LINK: ${{ secrets.TUNNEL_STARTUP_LINK }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Upload EDC Server log file
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: EdcServerLog and env file
          path: |
            ./edc_server.log 
            ./test/.env
      - name: Generate jacocoTestReport and run Sonar
        if: always()
        run: |
          ./gradlew jacocoTestReport --no-daemon --stacktrace
          ./gradlew sonarqube --no-daemon --stacktrace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Upload Build Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: JaCoCoResultsTest
          path: ./build/reports/*

  summary:
    runs-on: ubuntu-latest
    if: success()
    needs:
      - testing-and-sonar
    steps:
      - name: Summary of this workflow's overall outcome
        run: exit 0
