name: TemurinBase

on:
  workflow_dispatch:

jobs:
  build-and-push-base-image:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Create the EDC spec
        run: ./gradlew dataland-connector:resolve --no-daemon
      - name: Copy the gradle cache into the workspace
        run: cp -r /home/runner/.gradle ./gradlecache
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build an eclipse temurin base image and push it to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./baseDockerfiles/temurinBaseImageDockerfile
          tags: ghcr.io/d-fine/datalandedc/temurinbase:latest
          push: true
